services:
  pursuit-alert:
    image: chrismuntean/pursuit-alert:latest
    privileged: true
    ports:
      - "8501:8501"
    volumes:
      - logs:/usr/src/app/logs
      - ./Pursuit_Alert.py:/usr/src/app/Pursuit_Alert.py
      - ./pages/Settings.py:/usr/src/app/pages/Settings.py

volumes:
  logs:
