version: '3.8'

services:
  pursuit-alert:
    # UNCOMMENT BELOW TO BUILD YOUR OWN IMAGE WITH "docker compose up --build"
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #  platforms:
    #    - linux/amd64
    #    - linux/arm64
    image: chrismuntean/pursuit-alert:v0.1.0-beta # Tag specification
    ports:
      - "8501:8501"
    volumes:
      - logs:/usr/src/app/logs # Mounting persistent logs volume

volumes:
  logs: # Named volume for plate logs